generic:
  log:
    format: "[%d{yyyy-MM-dd'T'HH:mm:ss.SSS}] [%-5p] [thread=%t] [class=%C %L] %m%n"
quarkus:
  package:
    type: uber-jar
    output-name: rmi-ac
  http:
    non-application-root-path: "/"
    port: ${SERVER_PORT:8082}
    test-port: 8080
    test-timeout: 10s
    cors:
      ~: ${CORS_ENABLED:true}
      origins: ${CORS_ORIGINS:*}
      headers: ${CORS_HEADERS}
  hibernate-orm:
    packages: com.example.pojo
    active: false
    "postgresql":
      datasource: "postgresql"
      packages: ${quarkus.hibernate-orm.packages}
      active: false
      log:
        sql: false
      database:
        generation: update
    "oracle":
      datasource: "oracle"
      packages: ${quarkus.hibernate-orm.packages}
      active: false
      log:
        sql: false
      database:
        generation: update
  datasource:
    db-kind: h2
    username: is_not_used
    password: is_not_used
    jdbc:
      url: jdbc:h2:mem:inventory
      max-size: 10
    "oracle":
      db-kind: oracle
      active: false
      username: ${DB_USERNAME:geneva_admin}
      password: ${DB_PASSWORD:geneva_admin}
      jdbc:
        url: ${DB_URL:jdbc:oracle:thin:@10.109.32.82:1521/NRMDEV}
        max-size: 10
    "postgresql":
      active: false
      db-kind: postgresql
      username: ${DB_USERNAME:ocs_superuser}
      password: ${DB_PASSWORD:ocs_superuser}
      jdbc:
        url: ${DB_URL:jdbc:postgresql://10.109.32.82:1521/pgtest}
        max-size: 10

  log:
    level: INFO
    min-level: ALL
    console:
      format: ${generic.log.format}
    file:
      enable: true
      format: ${generic.log.format}
      path: ${VOLUME_LOGS:../../../../logs}/application/rmi-ac.log
      rotation:
        file-suffix: .yyyy-MM-dd
    category:
      "org.hibernate":
        level: trace

"%oracle":
  quarkus:
    hibernate-orm:
      "oracle":
        active: true
    datasource:
      "oracle":
        active: true
"%postgresql":
  quarkus:
    hibernate-orm:
      "postgresql":
        active: true
    datasource:
      "postgresql":
        active: true
"%test":
  quarkus:
    http:
      port: 9090
      access-log:
        enabled: true
    log:
      console:
        level: DEBUG
#  hibernate-orm:
#    active: true
#    log:
#      sql: true
#    database:
#      generation: drop-and-create